import React from 'react';
import { Document, Page, Text, View, StyleSheet, Link, Image } from '@react-pdf/renderer';
import siteData from "../data.json";
import { Svg, Path } from '@react-pdf/renderer';

// Embed logo as base64 (truncated for brevity, use full string in real code)
const logoBase64 =
  "iVBORw0KGgoAAAANSUhEUgAAB9AAAAjECAYAAAD0N/QdAAAACXBIWXMAACHKAAAhygE7RgpNAAAA..."; // Replace with full string from logo.png.b64
const logoLink = "https://cubeunity.com/services/tech-cost-optimization";

// Create styles with website colors
const styles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: '#fff',
  },
  header: {
    marginBottom: 16,
    textAlign: 'center',
  },
  logo: {
    width: 80,
    height: 80,
    margin: '0 auto',
    marginBottom: 10,
  },
  title: {
    fontSize: 26,
    color: '#6B78CB', // primary
    fontWeight: 'bold',
    marginBottom: 6,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 18,
    color: '#6B78CB', // blue only
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  text: {
    fontSize: 12,
    marginBottom: 10,
    color: '#333',
    textAlign: 'center',
  },
  section: {
    margin: 10,
    padding: 18,
    borderRadius: 12,
    backgroundColor: '#F7FAFC', // light blue/gray
    boxShadow: '0 2px 8px #eee',
  },
  savings: {
    fontSize: 22,
    color: '#00BD03', // green text
    textAlign: 'center',
    marginVertical: 18,
    backgroundColor: '#F3F4F6', // light gray
    padding: 14,
    borderRadius: 10,
    fontWeight: 'bold',
  },
  alternativeSection: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 16,
    marginBottom: 16,
    boxShadow: '0 1px 4px #eee',
  },
  alternativeTitle: {
    fontSize: 15,
    color: '#6B78CB', // blue only
    marginBottom: 6,
    fontWeight: 'bold',
  },
  alternativeItem: {
    marginLeft: 18,
    marginBottom: 8,
  },
  alternativeText: {
    fontSize: 12,
    color: '#4A5568',
    marginBottom: 2,
  },
  alternativeLink: {
    fontSize: 11,
    color: '#6B78CB', // blue link
    textDecoration: 'underline',
    marginLeft: 15,
  },
  ctaSection: {
    marginTop: 24,
    padding: 18,
    backgroundColor: '#F3E8FB', // pink bg
    borderRadius: 12,
    textAlign: 'center',
  },
  ctaText: {
    fontSize: 16,
    color: '#6B78CB', // blue only
    marginBottom: 10,
    fontWeight: 'bold',
  },
  link: {
    color: '#6B78CB', // blue link
    textDecoration: 'underline',
    fontSize: 13,
    marginTop: 8,
  },
  logoLink: {
    alignSelf: 'center',
    marginBottom: 10,
  },
  footer: {
    marginTop: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#888',
  },
});

export interface OpenSourceAlternative {
  name: string;
  url?: string;
  description?: string;
}

export interface SelectedTool {
  name: string;
  category: string;
  costPerUser: number;
}

export interface AlternativeTool {
  toolName: string;
  alternatives: OpenSourceAlternative[];
  costPerUser: number;
}

interface CalculatorPDFProps {
  teamSize: number;
  selectedTools: SelectedTool[];
  totalSavingsPerYear: number;
  openSourceAlternatives: AlternativeTool[];
  logoBase64?: string;
}

const CalculatorPDF: React.FC<CalculatorPDFProps> = ({
  teamSize,
  selectedTools,
  totalSavingsPerYear,
  openSourceAlternatives,
  logoBase64,
}) => {
  const { websiteUrl, companyName } = siteData;
  
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          {logoBase64 && (
            <Link src={logoLink} style={styles.logoLink}>
              <Image src={`data:image/png;base64,${logoBase64}`} style={styles.logo} />
            </Link>
          )}
          <Text style={styles.title}>Open Source Savings Report</Text>
          <Text style={styles.text}>Generated by {companyName}</Text>
        </View>
        
        <View style={styles.section}>
          <Text style={styles.subtitle}>Recommended Open Source Alternatives</Text>
          <Text style={styles.text}>Team Size: {teamSize} members</Text>
          <Text style={styles.savings}>Total Annual Savings Potential: ${totalSavingsPerYear.toLocaleString()}</Text>
          {openSourceAlternatives.map((item, index) => (
            <View key={index} style={styles.alternativeSection}>
              <Text style={styles.alternativeTitle}>
                {item.toolName} (${item.costPerUser}/user/month)
              </Text>
              {item.alternatives.map((alt, altIndex) => (
                <View key={altIndex} style={styles.alternativeItem}>
                  <Text style={styles.alternativeText}>• {alt.name}</Text>
                  <Text style={styles.alternativeText}>{alt.description}</Text>
                  {alt.url && (
                    <Link src={alt.url} style={styles.alternativeLink}>
                      Visit website →
                    </Link>
                  )}
                </View>
              ))}
            </View>
          ))}
        </View>

        <View style={styles.ctaSection}>
          <Text style={styles.ctaText}>Ready to Start Your Open Source Journey?</Text>
          <Text style={styles.text}>
            Our team can help you plan and execute a smooth transition to open source alternatives.
          </Text>
          <Link src={`${websiteUrl}/contact`} style={styles.link}>
            Schedule a Free Consultation →
          </Link>
        </View>

        <View style={styles.footer}>
          <Text>Visit us at <Link src={websiteUrl} style={styles.link}>{websiteUrl}</Link></Text>
          <Text>Copyright © {new Date().getFullYear()} {companyName}. All rights reserved.</Text>
        </View>
      </Page>
    </Document>
  );
};

export default CalculatorPDF; 