import React from 'react';
import { Document, Page, Text, View, StyleSheet, Link, Image } from '@react-pdf/renderer';
import siteData from "../data.json";
import { Svg, Path } from '@react-pdf/renderer';

// Create styles with website colors
const styles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 20,
    textAlign: 'center',
  },
  title: {
    fontSize: 24,
    marginBottom: 10,
  },
  text: {
    fontSize: 12,
    marginBottom: 10,
  },
  section: {
    margin: 10,
    padding: 10,
    borderRadius: 8,
  },
  subtitle: {
    fontSize: 18,
    marginBottom: 10,
    color: '#2D3748',
  },
  table: {
    width: 'auto',
    marginVertical: 10,
    borderRadius: 8,
    backgroundColor: '#F7FAFC',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    borderBottomStyle: 'solid',
    alignItems: 'center',
    minHeight: 30,
  },
  tableHeader: {
    backgroundColor: '#EDF2F7',
  },
  tableHeaderText: {
    color: '#2D3748',
    fontSize: 12,
    fontWeight: 'bold',
  },
  tableCell: {
    flex: 1,
    padding: 8,
    fontSize: 11,
  },
  savings: {
    fontSize: 20,
    color: '#276749',
    textAlign: 'center',
    marginVertical: 15,
    backgroundColor: '#F0FFF4',
    padding: 10,
    borderRadius: 8,
  },
  alternativeSection: {
    backgroundColor: '#F7FAFC',
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
  },
  alternativeTitle: {
    fontSize: 14,
    color: '#2D3748',
    marginBottom: 5,
    fontWeight: 'bold',
  },
  alternativeItem: {
    marginLeft: 15,
    marginBottom: 8,
  },
  alternativeText: {
    fontSize: 11,
    color: '#4A5568',
    marginBottom: 3,
  },
  alternativeLink: {
    fontSize: 10,
    color: '#2B6CB0',
    textDecoration: 'underline',
    marginLeft: 15,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
  },
  link: {
    color: '#2B6CB0',
    textDecoration: 'underline',
  },
  ctaSection: {
    marginTop: 20,
    padding: 15,
    backgroundColor: '#EDF2F7',
    borderRadius: 8,
    textAlign: 'center',
  },
  ctaText: {
    fontSize: 14,
    color: '#2D3748',
    marginBottom: 10,
    fontWeight: 'bold',
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    borderBottomStyle: 'solid',
    marginVertical: 15,
  },
});

export interface OpenSourceAlternative {
  name: string;
  url?: string;
  description?: string;
}

export interface SelectedTool {
  name: string;
  category: string;
  costPerUser: number;
}

export interface AlternativeTool {
  toolName: string;
  alternatives: OpenSourceAlternative[];
  costPerUser: number;
}

interface CalculatorPDFProps {
  teamSize: number;
  selectedTools: SelectedTool[];
  totalSavingsPerYear: number;
  openSourceAlternatives: AlternativeTool[];
}

const CalculatorPDF: React.FC<CalculatorPDFProps> = ({
  teamSize,
  selectedTools,
  totalSavingsPerYear,
  openSourceAlternatives,
}) => {
  const { websiteUrl, companyName } = siteData;
  
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Open Source Cost Savings Report</Text>
          <Text style={styles.text}>Generated by {companyName}</Text>
        </View>
        
        <View style={styles.section}>
          <Text style={styles.text}>Team Size: {teamSize} members</Text>
          
          <View style={styles.divider} />
          
          <Text style={styles.subtitle}>Selected Tools Summary</Text>
          <View style={styles.table}>
            <View style={[styles.tableRow, styles.tableHeader]}>
              <Text style={[styles.tableCell, styles.tableHeaderText]}>Tool</Text>
              <Text style={[styles.tableCell, styles.tableHeaderText]}>Category</Text>
              <Text style={[styles.tableCell, styles.tableHeaderText]}>Annual Cost</Text>
            </View>
            {selectedTools.map((tool, index) => (
              <View key={index} style={styles.tableRow}>
                <Text style={styles.tableCell}>{tool.name}</Text>
                <Text style={styles.tableCell}>{tool.category}</Text>
                <Text style={styles.tableCell}>
                  ${(tool.costPerUser * teamSize * 12).toLocaleString()}
                </Text>
              </View>
            ))}
          </View>

          <View style={styles.savings}>
            <Text>Total Annual Savings Potential</Text>
            <Text>${(totalSavingsPerYear).toLocaleString()}</Text>
          </View>

          <View style={styles.divider} />

          <Text style={styles.subtitle}>Recommended Open Source Alternatives</Text>
          {openSourceAlternatives.map((item, index) => (
            <View key={index} style={styles.alternativeSection}>
              <Text style={styles.alternativeTitle}>
                {item.toolName} (${item.costPerUser}/user/month)
              </Text>
              {item.alternatives.map((alt, altIndex) => (
                <View key={altIndex} style={styles.alternativeItem}>
                  <Text style={styles.alternativeText}>• {alt.name}</Text>
                  <Text style={styles.alternativeText}>{alt.description}</Text>
                  {alt.url && (
                    <Link src={alt.url} style={styles.alternativeLink}>
                      Visit website →
                    </Link>
                  )}
                </View>
              ))}
            </View>
          ))}
        </View>

        <View style={styles.ctaSection}>
          <Text style={styles.ctaText}>Ready to Start Your Open Source Journey?</Text>
          <Text style={styles.text}>
            Our team can help you plan and execute a smooth transition to open source alternatives.
          </Text>
          <Link src={`${websiteUrl}/contact`} style={styles.link}>
            Schedule a Free Consultation →
          </Link>
        </View>

        <View style={styles.footer}>
          <Text style={styles.text}>
            Visit us at{' '}
            <Link src={websiteUrl} style={styles.link}>
              {websiteUrl}
            </Link>
          </Text>
          <Text style={[styles.text, { fontSize: 10, marginTop: 5 }]}>
            Copyright © {new Date().getFullYear()} {companyName}. All rights reserved.
          </Text>
        </View>
      </Page>
    </Document>
  );
};

export default CalculatorPDF; 